package org.example.templates;

import java.util.HashMap;
import java.util.Map;
import org.reflections.Reflections;
import org.example.models.generated.AutoGeneratedModel;

/**
* Auto-generated registry of on-chain models
*/
public class ModelRegistry {
private static final Map<String, Class<?>> registry = new HashMap<>();
static {
Reflections reflections = new Reflections("org.example.templates");
for (Class<?> c : reflections.getTypesAnnotatedWith(AutoGeneratedModel.class)) {
registry.put(c.getSimpleName(), c);
}
}

/** Lookup the Java bridge class for a given struct name */
public static Class<?> getModel(String structName) {
return registry.get(structName);
}
}
